### ISSUE TITLE
Dependency issue between modin and kedro-dataframe-dropin

### ISSUE THREAD

**Issue by lucasjamar** [mzjp2/kedro-dataframe-dropin#9]
Hi!

Super cool package. Its really cool that you are offering the possibility to use modin to Kedro users. I just wanted to point out that there seems to be a dependency issue when installing. kedro-dataframe-dropin requires pandas>=1.2.0 whereas the latest version of modin requires pandas==1.1.5. I am therefore unable to install kedro-dataframe-dropin. Is it perhaps possible to downgrade kedro-dataframe-dropin to pandas 1.1.5? Thanks.

Installation error message:
![image](https://user-images.githubusercontent.com/39372418/106600235-6885e700-655a-11eb-9528-8fce3103d30a.png)

Modin requirements:
https://github.com/modin-project/modin/blob/master/requirements.txt

**Comment by mzjp2** [comment]
Hey Lucas,

Thanks very much for the feedback snd bug report. Much appreciated. I’ll
unpin the pandas requirements (still learning my way around poetry) and
release a new version ASAP (by the end of today?)

**Comment by lucasjamar** [comment]
Thanks a lot for the improvement!

**Comment by mzjp2** [comment]
@lucasjamar Should be fixed if you `pip install kedro-dataframe-dropin==0.2.0` :)

By the way - would love to know your use case for this, if you're interested in having a chat.
